#!/usr/bin/env python3
"""Vectorize public/emblem.png into real SVG path data for the trace-loader animation.
Requires potrace (brew install potrace)."""
import re
import subprocess
import os
from PIL import Image

SRC = "public/emblem.png"
WORKDIR = "/tmp/emblem-trace"
NOISE_THRESHOLD = 150  # drop path segments shorter than this many characters (specks)

os.makedirs(WORKDIR, exist_ok=True)

# 1. Build a high-contrast silhouette bitmap from the emblem's alpha channel
img = Image.open(SRC).convert("RGBA")
w, h = img.size
scale = 3
img = img.resize((w * scale, h * scale), Image.LANCZOS)
alpha = img.split()[3]

bw = alpha.point(lambda p: 0 if p > 128 else 255, mode='L').convert('1')
pbm_path = f"{WORKDIR}/silhouette.pbm"
bw.save(pbm_path)

# 2. Trace it
svg_path = f"{WORKDIR}/traced.svg"
subprocess.run(["potrace", pbm_path, "-s", "-o", svg_path, "--tight", "-O", "0.4"], check=True)

# 3. Merge potrace's separate <path> elements into one, dropping noise specks.
# potrace pretty-prints each d attribute across multiple lines, so raw
# newlines/extra whitespace must be collapsed before embedding as a single
# JS string literal (an embedded literal newline is a JS syntax error).
content = open(svg_path).read()
raw_paths = re.findall(r'<path d="([^"]+)"/>', content)
paths = [" ".join(d.split()) for d in raw_paths]
kept = [d for d in paths if len(d) >= NOISE_THRESHOLD]
combined_d = " ".join(kept)

viewbox_match = re.search(r'viewBox="([^"]+)"', content)
transform_match = re.search(r'<g transform="([^"]+)"', content)

# 4. Write the React data module
out = f"""// Real vectorized path data for the club's wings+volleyball emblem.
// Generated by scripts/generate-emblem-path.py from public/emblem.png via potrace.
// Do not hand-edit — regenerate from the source PNG if the logo changes.

export const EMBLEM_VIEWBOX = "{viewbox_match.group(1)}";
export const EMBLEM_TRANSFORM = "{transform_match.group(1)}";
export const EMBLEM_PATH_D = "{combined_d}";
"""

with open("src/data/emblemPath.js", "w") as f:
    f.write(out)

print(f"Kept {len(kept)}/{len(paths)} path segments ({len(combined_d)} chars)")
print("Wrote src/data/emblemPath.js")
